# Environment-Specific Deployment Configuration
# Production, Staging, Development branches

services:
  # Production Environment (main branch)
  - type: web
    name: tag-checker-prod
    env: node
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: TARGET_ACCOUNT
        value: adtaxi
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_ANALYTICS
        value: true
    domains:
      - checker.yourdomain.com
      - www.checker.yourdomain.com
    autoDeploy: true
    branch: main

  # Staging Environment (develop branch)
  - type: web
    name: tag-checker-staging
    env: node
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: staging
      - key: TARGET_ACCOUNT
        value: adtaxi-staging
      - key: LOG_LEVEL
        value: debug
      - key: ENABLE_ANALYTICS
        value: false
    domains:
      - staging.checker.yourdomain.com
    autoDeploy: true
    branch: develop

  # Development Environment (feature branches)
  - type: web
    name: tag-checker-dev
    env: node
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: development
      - key: TARGET_ACCOUNT
        value: adtaxi-dev
      - key: LOG_LEVEL
        value: debug
      - key: ENABLE_ANALYTICS
        value: false
      - key: DEBUG_MODE
        value: true
    domains:
      - dev.checker.yourdomain.com
    autoDeploy: false  # Manual deployment for dev
    branch: feature/*

  # Production Static Assets (CDN)
  - type: static
    name: static-assets
    buildCommand: |
      # Build optimized assets
      mkdir -p assets
      cp -r web/public/* assets/
      # Optimize images, minify CSS/JS here
    staticPublishPath: ./assets
    headers:
      - path: /*
        headers:
          - name: Cache-Control
            value: public, max-age=31536000, immutable
    domains:
      - cdn.yourdomain.com
    autoDeploy: true
    branch: main

  # Staging Static Site (for testing)
  - type: static
    name: staging-docs
    buildCommand: |
      mkdir -p staging-docs
      echo "<h1>Staging Documentation</h1>" > staging-docs/index.html
      echo "<p>Last updated: $(date)</p>" >> staging-docs/index.html
    staticPublishPath: ./staging-docs
    domains:
      - staging-docs.yourdomain.com
    autoDeploy: true
    branch: develop