services:
  - type: web
    name: tag-management-checker
    env: node
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: TARGET_ACCOUNT
        value: adtaxi
    autoDeploy: true